# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

on:
  push:
    branches: [ main ]

services:
  s3webshop:
    image: s3webshop
    build:
      context: .
      dockerfile: S3-webshop/Dockerfile
    ports:
      - 5000:5000
